### ISSUE TITLE
News Detail: "External News Link" renamed to "External Link"

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/hscrb-website#100]
On the News Detail template, the "External News Link" should be renamed to "External Link"

**Comment by maxfenton** [comment]
![Screen Shot 2019-04-11 at 1 41 39 PM](https://user-images.githubusercontent.com/906502/55979165-8be1f280-5c5f-11e9-898b-f6e031da1f34.png)

- [ ] change label of External News Link layout of News FC fields #43

**Comment by BSBaker2** [comment]
This applies to the flexible one in the body, not the one that the bottom that is restricted to the bottom
