### ISSUE TITLE
Event Detail - Guest Info FE 

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/hscrb-website#105]
On an event detail page, the Guest info is showing as an upcoming event below the event detail instead of the right rail

https://dev-hscrb.pantheonsite.io/event/juergen-knoblich/

![Screen Shot 2019-04-16 at 2.23.57 PM.png](https://images.zenhubusercontent.com/5a6633b54b5806bc2bc3c84d/b04083be-0b26-4099-8126-e77adb99edef)

**Comment by maxfenton** [comment]
All set
