### ISSUE TITLE
When Header is white, make nav white as well.

### ISSUE THREAD

**Issue by samWinfield** [bluecadet/hscrb-website#122]
The white background should extend to nav when nav is set to white.

![image](https://user-images.githubusercontent.com/19784290/56592704-3095f580-65b9-11e9-9d38-6c58658f5bbe.png)

**Comment by maxfenton** [comment]
@samWinfield Does that happen only on Single Person pages, or other places, too?

**Comment by samWinfield** [comment]
I think it's only doing it on single person pages. It doesn't do it on News or Events.

**Comment by maxfenton** [comment]
@samWinfield Great, thanks

**Comment by samWinfield** [comment]
This looks good! Closing. Thanks!
