### ISSUE TITLE
Featured News & Events Block

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/hscrb-website#13]
- [x] Up to 2 Upcoming Event Teasers
- [x] "No Upcoming Events" message

**Comment by maxfenton** [comment]
If there are no upcoming events, should the CTA button text change from "View All Events" ?

**Comment by BSBaker2** [comment]
@samWinfield can you weigh in?

**Comment by samWinfield** [comment]
@maxfenton Is it possible to hide it? We don't have an event archive, right?

**Comment by samWinfield** [comment]
I don't really have a good suggestion, I'm open to the path of least resistance here.

**Comment by maxfenton** [comment]
Design calls for up to 2 upcoming events. Same logic as the home page, minus the relationship field (on Home) that overrides those two. So they get pulled from a transient; I just have to solve a Post() conversion issue and de-duplicate the query logic for Home, Events (Archive), and this Upcoming Events widget.
