### ISSUE TITLE
Global ACF Planning

### ISSUE THREAD

**Issue by dirtystylus** [bluecadet/hscrb-website#59]
- decide when and when not to use Clone fields
- make a plan for Flexible Content fields (many inactive field groups, cloned into FC blocks on particular pages; one Page: Singles FC group)
- [x] develop fields local, commit acf-json, sync on dev; make entries on dev

**Comment by maxfenton** [comment]
![screen shot 2019-02-22 at 6 07 06 pm](https://user-images.githubusercontent.com/906502/53276348-b63a1980-36cc-11e9-8cf7-b593bd6caa72.png)

Current status of ACF fields with ACF-JSON in a feature branch for now.

- basic fields for the parts of the Lab that are in InVision and can be guessed
- basic fields for News, Publications, and Faculty, and some of Home

Working on a list of clarifying questions for things that came up while doing those.

**Comment by maxfenton** [comment]
Global (Options) content:

- Footer -> #7 
- Links: Harvard Medical School. Harvard FAS, Social Links

**Comment by maxfenton** [comment]
2019-03-14
- [ ] decide on a variable name for `color_theme`
- [ ] work through Flexible Content on Lab sub-sections (#41) and then work towards single pages
- [ ] decide whether to have a `data` context variable that mimic the `post` or _only_ use `data` to pass to partials (cleaner)

**Comment by maxfenton** [comment]
- [ ] document Flexible Content fields in Github

**Comment by maxfenton** [comment]
- Single Pages and News Items have different Flexible Content fields with different names and different combinations of available fields
- All of those flexible content Layouts have names like `fc_gallery` which correspond to a Twig template of the same name.
- Every flexible content block is defined by a single, inactive, field group with a label like `FC: [Blockname]` 
- All flexible content Layouts have a _single_ field. a Clone of an inactive field group, and those Clone fields are all called `fc` (that name isn't used anywhere and does not need to be unique)

**Comment by maxfenton** [comment]
[HSCRB ACF 2019-03-22.pdf](https://github.com/bluecadet/hscrb-website/files/2998145/HSCRB.ACF.2019-03-22.pdf)

**Comment by maxfenton** [comment]
Closing this as conceptually done and implemented.
