### ISSUE TITLE
Wordpress: install Plugins

### ISSUE THREAD

**Issue by maxfenton** [bluecadet/hscrb-website#64]
- [x] Advanced Custom Fields Pro
- [x] Search & Filter Pro
- [x] Yoast

**Comment by maxfenton** [comment]
Updated ACF Pro with my own download link

**Comment by maxfenton** [comment]
- [ ] set up ACF Pro in composer.json with a BlueCadet licensed link

**Comment by dirtystylus** [comment]
@maxfenton I updated **composer.json** with the BC-licensed download
