### ISSUE TITLE
Upcoming Events (component)

### ISSUE THREAD

**Issue by maxfenton** [bluecadet/hscrb-website#74]
On Event Detail (#47), add an Upcoming Events module below the page content

- only show if there are upcoming events
- up to two upcoming events are shown (previews are the same as Events Landing #50)
- prescribed CTA button "View All Events" links to Events Landing

**Comment by maxfenton** [comment]
This is built

**Comment by dirtystylus** [comment]
@maxfenton Do we have an example for this?

**Comment by maxfenton** [comment]
@dirtystylus YIKES. I did _not_ do this module. I got confused. It's a quick one that I'll do tonight.
