### ISSUE TITLE
People post type notes

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/hscrb-website#77]
from a conversation with client 4.3.19

Need 3 types of People: Faculty, Staff, Trainees
 - all will have a bio
 - Should include a field to end their ORCID number
 - Image will be optional
 - job descriptions is a text field they enter themselves

Faculty can have multiple trainees working for them
Trainees can work for multiple faculty

Staff will have sub groups: teaching assistants, proctors, grad students, fellows

**Comment by dirtystylus** [comment]
@BSBaker2 I don‘t know that we need to explicitly have those subgroups in, say, a taxonomy. What Sam and I suggest is to create a repeater structure that allows for

* Group Header Text
* Person/Faculty relationship field (multiple)

So there could be multiple groups of faculty/staff and they just label those groups in the way that’s most meaningful to them. (Each lab currently presents their people differently and there’s no universal categories)

**Comment by maxfenton** [comment]
@dirtystylus Do _only_ Faculty have profile pages?

**Comment by maxfenton** [comment]
What is a Trainee?

**Comment by maxfenton** [comment]
Let’s crossref this with #43

**Comment by maxfenton** [comment]
Let’s crossref this with #38
