### ISSUE TITLE
Faculty ORCID info

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/hscrb-website#86]
Mary Todd [2:53 PM]
ORCIDs exist for faculty members but generally they are not claiming their articles. We should gather them anyway, as this should change in future:
Lee Rubin - https://orcid.org/0000-0002-8658-841X
Paola Arlotta - https://orcid.org/0000-0003-2184-2277
Kevin Eggan - https://orcid.org/0000-0003-4436-8467
Amy Wagers - https://orcid.org/0000-0002-0066-0485
Catalyst IDs are in the url of the faculty members’ profiles, and are effective in running publication queries.

**Comment by maxfenton** [comment]
- [ ] Change ORCID format from Number to Text (because of hyphens and `X`)
