### ISSUE TITLE
Remove images from Homepage News and Events teasers

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/hscrb-website#87]
Remove images from Homepage News and Events teasers

**Comment by maxfenton** [comment]
- [ ] check if these previews are generated from a shared component; if so, add a flag for images/none
- [ ] remove images from homepage news 
- [ ] remove images from homepage events

**Comment by maxfenton** [comment]
- [ ] remove image from all event previews

**Comment by samWinfield** [comment]
There's now a lot of extra space (combination of a couple elements' padding & margin) between events on the homepage. Looks like it's ".mb-xl" that's adding the extra 2.5rem of margin. Can we remove this?

**Comment by maxfenton** [comment]
@samWinfield Updated.
