### ISSUE TITLE
Homepage template: restrict color toggle of callout

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/hscrb-website#92]
on the homepage template restrict the callout from having toggle ability. All callouts on the homepage will be HSCRB related (i.e. red). Callouts everywhere else should have the toggle option

**Comment by maxfenton** [comment]
- [ ] update Callout component (#14) to only have sitewide flag in some places.

Question @BSBaker2 — should the sitewide flag _only_ exist for a callout that is on a Lab page? Are all callouts that are _not_ on a Lab sitewide?

If that's the case, I think we should make a separate Lab Callout component that clones a Callout component and adds that sitewide flag option. (@dirtystylus make sense?)

**Comment by dirtystylus** [comment]
Crimson is used for all non-lab internal destinations.
