### ISSUE TITLE
Add a Lede field on News Detail

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/hscrb-website#98]
Add a Lede field on News detail. on the FE it will show between the News title and the feature image (where the social links currently are)

@samWinfield any design direction for what it looks like on FE?

![News Lede.png](https://images.zenhubusercontent.com/5a6633b54b5806bc2bc3c84d/8b3cc927-7867-4d23-bd98-96212a34b1ea)

**Comment by maxfenton** [comment]
@BSBaker2 Does this lede show through on the News previews? Is that going to be the source of these placeholder excerpts on the Home and News pages?
![Screen Shot 2019-04-11 at 1 36 58 PM](https://user-images.githubusercontent.com/906502/55978889-eb8bce00-5c5e-11e9-8433-68862bf86755.png)
![Screen Shot 2019-04-11 at 1 37 52 PM](https://user-images.githubusercontent.com/906502/55978947-065e4280-5c5f-11e9-8b85-b9470c937c40.png)

**Comment by BSBaker2** [comment]
@samWinfield what are your thoughts? I could see it showing on the news preview because they did say they wanted control of what shows there rather than having it become a "read more..." situation

**Comment by samWinfield** [comment]
@BSBaker2 @maxfenton I think it should be the source of the excerpt for the news preview. 

For styling, we're using the ".bc-f-h3" class to define event subtitles. I think that same styling is appropriate for the News lede.
